name: C++ Ray Tracing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change configure permissions
      run: chmod +x ./configure
    - name: configure
      run: ./configure
    - name: make
      run: make
